/* tslint:disable */
/* eslint-disable */
/**
 * Guardrails API
 * Guardrails CRUD API
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CallException
 */
export interface CallException {
  /**
   *
   * @type {any}
   * @memberof CallException
   */
  message?: any;
}

/**
 * Check if a given object implements the CallException interface.
 */
export function instanceOfCallException(value: string | {
  [key: string]: any;
}): boolean {
  if (typeof value === 'string') {
    return true
  } else if (value["message"]) {
    return true;
  }
  return false;
}

export function CallExceptionFromJSON(json: string | { [key: string]: any; }): string | CallException {
  return CallExceptionFromJSONTyped(json, false);
}

export function CallExceptionFromJSONTyped(
  json: string | {
    [key: string]: any;
  },
  ignoreDiscriminator: boolean,
): string | CallException {
  if (json == null) {
    return json;
  } else if (typeof json === 'string') {
    return json;
  }
  return {
    ...json,
    message: json["message"] == null ? undefined : json["message"]
  };
}

export function CallExceptionToJSON(value?: string | CallException | null): string | { [key: string]: any; } | null | undefined {
  if (value == null) {
    return value;
  } else if (typeof value === 'string') {
    return value;
  }
  return {
    ...value,
    message: value["message"]
  };
}
