/* tslint:disable */
/* eslint-disable */
/**
 * Guardrails API
 * Guardrails CRUD API
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Call } from "./Call";
import { CallFromJSON, CallToJSON } from "./Call";

/**
 *
 * @export
 * @interface GuardHistory
 */
export interface GuardHistory {
  /**
   *
   * @type {string}
   * @memberof GuardHistory
   */
  $ref?: string;
}

/**
 * Check if a given object implements the GuardHistory interface.
 */
export function instanceOfGuardHistory(value: { [key: string]: any }): boolean {
  return true;
}

export function GuardHistoryFromJSON(json: any): GuardHistory | Call[] {
  return GuardHistoryFromJSONTyped(json, false);
}

export function GuardHistoryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GuardHistory | Call[] {
  if (json == null) {
    return json;
  } else if (Array.isArray(json)) {
    return json.map(CallFromJSON);
  }
  return {
    $ref: json["$ref"] == null ? undefined : json["$ref"],
  };
}

export function GuardHistoryToJSON(value?: Call[] | GuardHistory | null): any {
  if (value == null) {
    return value;
  } else if (Array.isArray(value)) {
    return value.map(CallToJSON);
  }
  return {
    $ref: value["$ref"],
  };
}
