/* tslint:disable */
/* eslint-disable */
/**
 * Guardrails API
 * Guardrails CRUD API
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Reask } from "./Reask";
import { ReaskFromJSON, ReaskToJSON } from "./Reask";

/**
 *
 * @export
 * @interface OutputsValidationResponse
 */
export type OutputsValidationResponse = string | Reask | Record<string, any>;

/**
 * Check if a given object implements the OutputsValidationResponse interface.
 */
export function instanceOfOutputsValidationResponse(value: object): boolean {
  return true;
}

export function OutputsValidationResponseFromJSON(
  json: any,
): OutputsValidationResponse {
  return OutputsValidationResponseFromJSONTyped(json, false);
}

export function OutputsValidationResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OutputsValidationResponse {
  if (json == null) {
    return json;
  } else if (typeof json === 'string') {
    return json;
  } else if (json.incorrectValue && json.failResults) {
    return ReaskFromJSON(json);
  }
  return json;
}

export function OutputsValidationResponseToJSON(
  value?: OutputsValidationResponse | null,
): any {
  if (value == null) {
    return value;
  } else if (typeof value === 'string') {
    return value;
  } else if (value.incorrectValue && value.failResults) {
    return ReaskToJSON(value);
  }
  return value;
}
